### PR TITLE
Async Validation and prevent activity auto closing when completed

### PR DESCRIPTION
**Pull request by frostymarvelous**
Changed validation to use a callback therefore allowing for async validation
Removed finishing of activity when form is completed

fixes https://github.com/HeinrichReimer/material-singleinputform/issues/12 and https://github.com/HeinrichReimer/material-singleinputform/issues/11

### CODE REVIEW

**Comment by HeinrichReimer** [comment]
Overall veeery nice pull request!!!
Just two suggestions:
1. Move `StepCheckerCallback` in `Step.java`
2. Give users the ability to use `public void check(..., StepCheckerCallback callback) {}` or `
    public boolean check(...) {}`. I'm not yet sure how to implement this but it should work with an abstract class. Any thoughts on this?
Thank you!

**Comment by frostymarvelous** [comment]
No idea why, I almost missed the notifications. I will check and see what I can implement in the mean time.

**Comment by frostymarvelous** [comment]
As per your suggestions, 

1. Done
2. I am thinking rather than changing the API totally like I have and having to bump the version number totally, I can make each `Step` accept the original `StepChecker` and add another constructor `StepCheckerAsync` which implements the changes I made. That way, we allow the user the flexibility and maintain the original Major Version of 2.

**Comment by frostymarvelous** [comment]
Done. Kindly review.

Also, I think we need to move to the builder pattern. The constructors have become more cumbersome. If you do merge this pull, I will work on it.

**Comment by HeinrichReimer** [comment]
Ok, really awsome changes. It presumably sounds like I'm a smart aleck, but I heve still some little points to mention:
1. Move `StepCheckerCallback` into Step.java
2. `ProgressDialog`s are a bit old-school and also userunfriendly and hard to style. Let's change that for a simple layout: It should be a `FrameLayout` and a centered, vertical orientated `LinearLayout` in it. In the `LinearLayout` there should be a horizontally centered `ProgressBar` and a horizontally centered `TextView` with a customizable "Loading..." text. Both the `ProgressBar` and the `TextView` should be colored based on the theme colors.
Thumbs up for your work!

**Comment by HeinrichReimer** [comment]
BTW, great way to achive consistency AND new features using `StepChecker` and `StepCheckerAsync` :+1:

**Comment by HeinrichReimer** [comment]
@frostymarvelous `Builder` pattern belongs to #8

**Comment by frostymarvelous** [comment]
Oh, I didn't notice the StepCheckerCallback was out again. I did the work in a separate branch ahead of master and realised this, so I basically just copied all the files into the master branch. Fixed.

Are you sure you want us to implement the progress? I only used the progress dialog as part of the demo.

**Comment by frostymarvelous** [comment]
Why I ask is because I feel the library should focus on doing what it does best. We will be incurring technical debt by adding unrelated features.

**Comment by HeinrichReimer** [comment]
The `ProgressBar` should only be used if the validation is async. Either way progress indication and a 'completed'-screen are very common uses and therefore belong in this library IMHO. Would also be nice if we swap the `ProgessBar` with an `ImageView` showing a big check mark to indicate the end of the form. I await my summer holidays, I'll be able to work on the library then.

**Pull request closed without merging**
